server:
  port: 8080

spring:
  application:
    name: lisboa
  main:
    banner-mode: off
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin

app:
  version: @project.version@
  integration:
    email:
      url: ${AGENT_URL}
    agent:
      url: ${AGENT_URL}
