server:
  port: 8080

spring:
  application:
    name: lisboa
  main:
    banner-mode: off
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin

app:
  version: @project.version@
  integration:
    email:
      url: ${EMAIL_URL}
      emailV1Uri: /api/v1/email
      typeEmailV1Uri: /api/v1/email-type
    agent:
      url: ${AGENT_URL}
      v1BaseUri: /api/v1/question
      connectTimeout: ${AGENT_CONNECT_TIMEOUT:3s}
      readTimeout: ${AGENT_READ_TIMEOUT:60s}